package template

// import "github.com/GuilhermeCaruso/mooncake/generator/models"

// type Template struct {
// 	f models.File
// }

// func NewTemplate(f models.File) *Template {
// 	return &Template{
// 		f: f,
// 	}
// }

const FILE_HEADER = `// ############################
// Generated by Mooncake
// Date: %s
// Source: %s
// ############################
`

const MOCK_STRUCTURE = `
type Mock%s%i struct {
	agent              *mooncake.MooncakeAgent
	internalController *InternalMock%s%k
}`

const CONSTRUCTOR_MOCK_FUNCTION = `
func NewMock%s%i(agent *mooncake.MooncakeAgent) *Mock%s%k {
	internal := new(Mock%s%k)
	internal.agent = agent
	internal.internalController = &InternalMock%s%k{
		mock: internal,
	}
	return internal
}`

const CONTRUCTOR_INTERNAL_MOCK = `
func (immi *Mock%s%k) Prepare() *InternalMock%s%k {
	return immi.internalController
}

type InternalMock%s%i struct {
	mock *Mock%s%k
}
`

const METHOD = `
func(m *Mock%s%k) %m(%p) (%r) {
	method := "%m"

	result := m.agent.GetCall(method)

	%a

	return
}
`

const INTERNAL_METHOD = `
func (im *InternalMock%s%k) %m(%p) *mooncake.AgentController {
	method := "%m"
	methodType := reflect.TypeOf((*Mock%s%k)(nil).%m)

	return im.mock.agent.SetCall(method, methodType)
}
`
